#pragma once
#include <algorithm>
#include <cassert>
#include <cstring>
#include <cstdio>
#include <cstdint>
#include <map>
#include <string>
#include <vector>
#include <deque>
struct String {std::string value;String(const char* s=""):value(s){}String(std::string s):value(s){}const char* c_str()const{return value.c_str();}bool startsWith(const char* s)const{return value.rfind(s,0)==0;}};
inline uint32_t fakeNow=0;inline uint32_t millis(){return fakeNow;}
constexpr int HIGH=1,WL_CONNECTED=3;inline void digitalWrite(int pin,int state){assert((pin==41||pin==45)&&state==HIGH);}
struct WifiFake {int state=WL_CONNECTED;bool sleep=true;int status(){return state;}int RSSI(){return -60;}void reconnect(){state=WL_CONNECTED;}bool getSleep(){return sleep;}void setSleep(bool s){sleep=s;}};inline WifiFake WiFi;
inline void configTzTime(const char*,const char*,const char*){}
using SemaphoreHandle_t=int*;inline int mutexToken=1;constexpr unsigned portMAX_DELAY=~0u;inline SemaphoreHandle_t xSemaphoreCreateMutex(){return &mutexToken;}inline void xSemaphoreTake(SemaphoreHandle_t s,unsigned){assert(s);}inline void xSemaphoreGive(SemaphoreHandle_t s){assert(s);}inline void vTaskDelay(unsigned n){fakeNow+=n;}inline unsigned pdMS_TO_TICKS(unsigned n){return n;}inline void vTaskDelete(void*){}constexpr int pdPASS=1;inline int taskResult=pdPASS;inline int xTaskCreate(void(*)(void*),const char*,unsigned,void*,int,void*){return taskResult;}
struct SPIClass{};inline SPIClass SPI;
constexpr int FILE_READ=1,FILE_WRITE=2,FILE_APPEND=3;
inline std::map<std::string,std::vector<uint8_t>> disk;inline bool card=true,writeFault=false,renameFault=false,readFault=false;inline unsigned openFiles=0,maxFiles=0;inline std::vector<std::string> deleted;
struct File {std::string path;size_t pos=0;bool opened=false;explicit operator bool()const{return opened;}unsigned size(){return disk[path].size();}int read(uint8_t* out,unsigned n){if(readFault)return 0;auto& b=disk[path];n=std::min<size_t>(n,b.size()-std::min(pos,b.size()));memcpy(out,b.data()+pos,n);pos+=n;return n;}size_t write(const uint8_t* in,size_t n){if(writeFault)return 0;auto& b=disk[path];b.insert(b.end(),in,in+n);pos+=n;return n;}void flush(){}void close(){if(opened){opened=false;--openFiles;}}};
struct SdFake {uint64_t freeBytes=1ull<<30;bool begin(int cs,SPIClass& spi,unsigned hz,const char* mount,unsigned files,bool format){assert(cs==41&&&spi==&SPI&&hz==4000000&&!strcmp(mount,"/sd")&&!format);maxFiles=files;return card;}void end(){assert(!openFiles);}bool exists(const char* p){return disk.count(p);}bool mkdir(const char*){return true;}uint64_t totalBytes(){return freeBytes+100;}uint64_t usedBytes(){return 100;}File open(const char* p,int mode){if(openFiles>=maxFiles)return {};if(mode==FILE_READ&&!disk.count(p))return {};if(mode==FILE_WRITE)disk[p].clear();++openFiles;return {p,mode==FILE_APPEND?disk[p].size():0,true};}bool remove(const char* p){deleted.push_back(p);return disk.erase(p)>0;}bool rename(const char* a,const char* b){if(renameFault||!disk.count(a)||disk.count(b))return false;disk[b]=disk[a];disk.erase(a);return true;}};inline SdFake SD;
struct NetworkClientSecure {void useBuiltinCACertBundle(){}void setHandshakeTimeout(unsigned n){assert(n==25);}};
struct Reply {int rc=200;std::vector<uint8_t> data;int length=-2;std::string range,location;size_t dropAt=~size_t(0);};
inline std::deque<Reply> replies;inline std::vector<std::string> ranges,urls;constexpr int HTTPC_DISABLE_FOLLOW_REDIRECTS=0;
struct HTTPClient {Reply reply;size_t pos=0;std::string range;bool begin(NetworkClientSecure&,String s){urls.push_back(s.value);return true;}void setConnectTimeout(int){}void setTimeout(int){}void setFollowRedirects(int){}void collectHeaders(const char**,int){}void addHeader(const char*,const char* s){range=s;}int GET(){ranges.push_back(range);assert(!replies.empty());reply=replies.front();replies.pop_front();pos=0;return reply.rc;}int getSize(){return reply.length==-2?reply.data.size():reply.length;}String header(const char* key){return String(!strcmp(key,"Location")?reply.location:reply.range);}HTTPClient* getStreamPtr(){return this;}int available(){return pos>=reply.dropAt?0:std::min<size_t>(reply.data.size()-pos,reply.dropAt-pos);}int read(uint8_t* b,size_t n){n=std::min<size_t>(n,available());memcpy(b,reply.data.data()+pos,n);pos+=n;return n;}bool connected(){return pos<reply.data.size()&&pos<reply.dropAt;}void end(){}};
// Test digest is deterministic; verifies hash checks/call ordering, not mbedTLS cryptography.
struct mbedtls_sha256_context {uint32_t h=2166136261u;};inline void mbedtls_sha256_init(mbedtls_sha256_context* c){c->h=2166136261u;}inline int mbedtls_sha256_starts(mbedtls_sha256_context* c,int){mbedtls_sha256_init(c);return 0;}inline int mbedtls_sha256_update(mbedtls_sha256_context* c,const uint8_t* b,size_t n){for(size_t i=0;i<n;++i)c->h=(c->h^b[i])*16777619u;return 0;}inline int mbedtls_sha256_finish(mbedtls_sha256_context* c,uint8_t* b){for(unsigned i=0;i<32;++i)b[i]=uint8_t((c->h>>(i%4*8))^i);return 0;}inline void mbedtls_sha256_free(mbedtls_sha256_context*){}
constexpr int ESP_OK=0;using esp_ota_handle_t=unsigned;struct esp_partition_t {uint32_t size=0x300000;};inline esp_partition_t target;inline bool beginFault=false,otaWriteFault=false,endFault=false,bootFault=false;inline unsigned beginCalls=0,bootCalls=0,abortCalls=0,endCalls=0;inline bool otaOpen=false;inline std::vector<uint8_t> flashed;
inline const esp_partition_t* esp_ota_get_next_update_partition(void*){return &target;}inline int esp_ota_begin(const esp_partition_t* p,unsigned bytes,unsigned* h){++beginCalls;assert(bytes<=p->size);if(beginFault)return -1;*h=1;otaOpen=true;flashed.clear();return ESP_OK;}inline int esp_ota_write(unsigned,const uint8_t* b,size_t n){assert(otaOpen);if(otaWriteFault)return -1;flashed.insert(flashed.end(),b,b+n);return ESP_OK;}inline int esp_ota_end(unsigned){assert(otaOpen);otaOpen=false;++endCalls;return endFault?-1:ESP_OK;}inline int esp_ota_abort(unsigned){assert(otaOpen);otaOpen=false;++abortCalls;return ESP_OK;}inline int esp_ota_set_boot_partition(const esp_partition_t*){assert(!otaOpen);++bootCalls;return bootFault?-1:ESP_OK;}
struct EspFake {bool restarted=false;uint32_t getPsramSize(){return 8*1048576;}void restart(){restarted=true;}};inline EspFake ESP;
