#include "LegacySave.h"
#include "../firmware/RPG_POKET_2/Narrative.h"
#include <cassert>
#include <cstring>
#include <cstdio>
#include <map>
#include <string>
#include <vector>
using namespace rpg;
struct AnwenStore{bool fail=false;std::map<std::string,std::vector<uint8_t>> data;Read read(const char* k,uint8_t* b){auto it=data.find(k);if(it==data.end())return Read::Missing;memcpy(b,it->second.data(),SAVE_SIZE);return Read::Ok;}bool write(const char* k,const uint8_t* b){if(fail)return false;data[k]=std::vector<uint8_t>(b,b+SAVE_SIZE);return true;}};
Game anwenHero(unsigned cls,unsigned race){auto g=create(cls,73);g.race=race;g.p.xp=265000;levelUp(g);g.tutorial=true;g.ruinsWins=3;g.guardianDefeated=true;g.dungeonClears=1;g.campaignFlags=7;g.rations=3;g.p.gold=600;assert(valid(g));return g;}
Game anwenReboot(const Game& g){assert(valid(g));uint8_t b[SAVE_SIZE],c[SAVE_SIZE];encode(g,17,b);assert(get16(b,4)==26);Game t;uint32_t seq;assert(decode(b,t,seq)==Decode::Ok&&seq==17);encode(t,17,c);assert(!memcmp(b,c,SAVE_SIZE));return t;}
int main(){
 unsigned runs=0;for(unsigned cls=0;cls<4;++cls)for(unsigned race=0;race<4;++race){unsigned order[]={0,1,2,3};do{auto g=anwenHero(cls,race);for(auto city:order){g.city=city;unsigned mission=4+city;assert(campaignContact(g)&&campaignMission(g)==mission&&!campaignError(g,mission)&&!contribution(g,city));auto before=g;assert(!memcmp(&g,&before,sizeof(g)));unsigned gold=g.p.gold,rations=g.rations,xp=g.p.xp;assert(!startCampaign(g,mission));g=anwenReboot(g);if(!campaignDonation(mission)){assert(g.campaignStage==mission&&!contribution(g,city)&&g.enemyId==campaignEnemy(mission));g.enemyHp=0;finish(g);g=anwenReboot(g);gold=g.p.gold;xp=g.p.xp;assert(resolveCampaign(g));}assert(contribution(g,city)&&g.phase==Phase::Home&&!g.campaignStage&&g.p.gold==gold+(city==3?-150:int(campaignGold(mission)))&&g.rations==rations-(city==0?3:0)&&g.p.xp==xp+1000);g=anwenReboot(g);before=g;assert(startCampaign(g,mission)&&!resolveCampaign(g)&&!memcmp(&g,&before,sizeof(g)));}assert(anwenReady(g)&&g.campaignFlags==127&&strstr(story::objective(g).place,"Liora"));++runs;}while(std::next_permutation(order,order+4));}
 for(unsigned mission:{5u,6u})for(auto outcome:{Phase::Lost,Phase::Fled}){auto g=anwenHero(0,0);g.city=campaignCity(mission);assert(!startCampaign(g,mission));g.phase=outcome;if(outcome==Phase::Lost)g.p.hp=0;auto gold=g.p.gold,xp=g.p.xp;g=anwenReboot(g);assert(resolveCampaign(g)&&!contribution(g,g.city)&&g.p.gold==gold&&g.p.xp==xp);g=anwenReboot(g);assert(!startCampaign(g,mission));}
 for(unsigned mission:{4u,7u}){auto g=anwenHero(2,1);g.city=campaignCity(mission);if(mission==4)g.rations=2;else g.p.gold=149;auto before=g;assert(startCampaign(g,mission)&&!memcmp(&g,&before,sizeof(g)));}
 for(unsigned invalid=0;invalid<7;++invalid){auto g=anwenHero(2,1);if(invalid==0)g.campaignFlags=3;if(invalid==1)g.p.level=17;if(invalid==2)g.city=1;if(invalid==3)g.tutorial=false;if(invalid==4)g.dungeonClears=0;if(invalid==5)g.discovery=1;if(invalid==6)g.phase=Phase::Hero;auto before=g;assert(startCampaign(g,4)&&!memcmp(&g,&before,sizeof(g)));}
 // Legacy21 reads without granting contributions; tampering cannot smuggle new flags/stages into old formats.
 auto g=anwenHero(1,2);uint8_t b[SAVE_SIZE];encode(g,1,b);legacyFormat(b,21);put32(b,124,crc(b,124));Game h;uint32_t seq;assert(decode(b,h,seq)==Decode::Ok&&h.campaignFlags==7&&!anwenReady(h));b[120]=15;put32(b,124,crc(b,124));assert(decode(b,h,seq)==Decode::Corrupt);b[120]=7;b[121]=5;put32(b,124,crc(b,124));assert(decode(b,h,seq)==Decode::Corrupt);g.campaignFlags=8;assert(!valid(g));g=anwenHero(1,2);g.campaignFlags=131;assert(!valid(g));
 // Donations are one atomic save: failed write/reboot leaves resources and proof at the previous checkpoint.
 for(unsigned mission:{4u,7u}){g=anwenHero(0,0);g.city=campaignCity(mission);AnwenStore store;Journal<AnwenStore> j(store);assert(j.load(h)==Load::Empty);assert(j.save(g));auto old=g;assert(!startCampaign(g,mission));store.fail=true;assert(!j.save(g));Journal<AnwenStore> boot(store);assert(boot.load(h)==Load::Ok&&h.p.gold==old.p.gold&&h.rations==old.rations&&!contribution(h,h.city));store.fail=false;assert(j.save(g)&&j.save(g));assert(boot.load(h)==Load::Ok&&contribution(h,h.city)&&startCampaign(h,mission));}
 // A normal encounter, visit, high level or conversation cannot earn a contribution.
 g=anwenHero(2,0);g.city=1;assert(begin(g,5));g.enemyHp=0;finish(g);assert(home(g)&&g.campaignFlags==7);auto before=g;story::objective(g);for(unsigned city=0;city<4;++city){assert(story::contributionPages(4+city)>1);unsigned rows=story::wrapStory(story::contributionBrief(4+city),18,[](unsigned,const char* line){assert(strlen(line)<=18);});assert(rows<=7);}assert(!memcmp(&g,&before,sizeof(g)));
 puts("PASS: Anwen384 ordered campaigns/all classes/races;4 real contributions, exact costs, gated previews, donation atomicity, combat loss/flee/resume, no duplicate rewards, save22/old21 protection, no inference from visits or ordinary fights");
}
