// Generated by tools/prepare_backgrounds.py; originals retained.
#pragma once
#include <stdint.h>
#include "AssetCatalog.h"
struct Backdrop {unsigned pixelId,paletteId;const uint8_t* pixels()const{return assetBytes(pixelId);} const uint16_t* palette()const{return reinterpret_cast<const uint16_t*>(assetBytes(paletteId));}};
#define bg_card_palette (reinterpret_cast<const uint16_t*>(assetBytes(0)))
#define bg_card_pixels (reinterpret_cast<const uint8_t*>(assetBytes(1)))
const Backdrop bg_card={1,0};
#define bg_tavern_palette (reinterpret_cast<const uint16_t*>(assetBytes(2)))
#define bg_tavern_pixels (reinterpret_cast<const uint8_t*>(assetBytes(3)))
const Backdrop bg_tavern={3,2};
#define bg_contract_palette (reinterpret_cast<const uint16_t*>(assetBytes(4)))
#define bg_contract_pixels (reinterpret_cast<const uint8_t*>(assetBytes(5)))
const Backdrop bg_contract={5,4};
#define bg_questconfirm_palette (reinterpret_cast<const uint16_t*>(assetBytes(6)))
#define bg_questconfirm_pixels (reinterpret_cast<const uint8_t*>(assetBytes(7)))
const Backdrop bg_questconfirm={7,6};
#define bg_choose_palette (reinterpret_cast<const uint16_t*>(assetBytes(8)))
#define bg_choose_pixels (reinterpret_cast<const uint8_t*>(assetBytes(9)))
const Backdrop bg_choose={9,8};
#define bg_guide_palette (reinterpret_cast<const uint16_t*>(assetBytes(10)))
#define bg_guide_pixels (reinterpret_cast<const uint8_t*>(assetBytes(11)))
const Backdrop bg_guide={11,10};
#define bg_camp_palette (reinterpret_cast<const uint16_t*>(assetBytes(12)))
#define bg_camp_pixels (reinterpret_cast<const uint8_t*>(assetBytes(13)))
const Backdrop bg_camp={13,12};
#define bg_village_palette (reinterpret_cast<const uint16_t*>(assetBytes(14)))
#define bg_village_pixels (reinterpret_cast<const uint8_t*>(assetBytes(15)))
const Backdrop bg_village={15,14};
#define bg_map_palette (reinterpret_cast<const uint16_t*>(assetBytes(16)))
#define bg_map_pixels (reinterpret_cast<const uint8_t*>(assetBytes(17)))
const Backdrop bg_map={17,16};
#define bg_character_palette (reinterpret_cast<const uint16_t*>(assetBytes(18)))
#define bg_character_pixels (reinterpret_cast<const uint8_t*>(assetBytes(19)))
const Backdrop bg_character={19,18};
#define bg_market_palette (reinterpret_cast<const uint16_t*>(assetBytes(20)))
#define bg_market_pixels (reinterpret_cast<const uint8_t*>(assetBytes(21)))
const Backdrop bg_market={21,20};
#define bg_shop_palette (reinterpret_cast<const uint16_t*>(assetBytes(22)))
#define bg_shop_pixels (reinterpret_cast<const uint8_t*>(assetBytes(23)))
const Backdrop bg_shop={23,22};
#define bg_buy_palette (reinterpret_cast<const uint16_t*>(assetBytes(24)))
#define bg_buy_pixels (reinterpret_cast<const uint8_t*>(assetBytes(25)))
const Backdrop bg_buy={25,24};
#define bg_inventory_palette (reinterpret_cast<const uint16_t*>(assetBytes(26)))
#define bg_inventory_pixels (reinterpret_cast<const uint8_t*>(assetBytes(27)))
const Backdrop bg_inventory={27,26};
#define bg_gearshop_palette (reinterpret_cast<const uint16_t*>(assetBytes(28)))
#define bg_gearshop_pixels (reinterpret_cast<const uint8_t*>(assetBytes(29)))
const Backdrop bg_gearshop={29,28};
#define bg_gearbag_palette (reinterpret_cast<const uint16_t*>(assetBytes(30)))
#define bg_gearbag_pixels (reinterpret_cast<const uint8_t*>(assetBytes(31)))
const Backdrop bg_gearbag={31,30};
#define bg_gearbuy_palette (reinterpret_cast<const uint16_t*>(assetBytes(32)))
#define bg_gearbuy_pixels (reinterpret_cast<const uint8_t*>(assetBytes(33)))
const Backdrop bg_gearbuy={33,32};
#define bg_gearequip_palette (reinterpret_cast<const uint16_t*>(assetBytes(34)))
#define bg_gearequip_pixels (reinterpret_cast<const uint8_t*>(assetBytes(35)))
const Backdrop bg_gearequip={35,34};
#define bg_forge_palette (reinterpret_cast<const uint16_t*>(assetBytes(36)))
#define bg_forge_pixels (reinterpret_cast<const uint8_t*>(assetBytes(37)))
const Backdrop bg_forge={37,36};
#define bg_upgrade_palette (reinterpret_cast<const uint16_t*>(assetBytes(38)))
#define bg_upgrade_pixels (reinterpret_cast<const uint8_t*>(assetBytes(39)))
const Backdrop bg_upgrade={39,38};
#define bg_skills_palette (reinterpret_cast<const uint16_t*>(assetBytes(40)))
#define bg_skills_pixels (reinterpret_cast<const uint8_t*>(assetBytes(41)))
const Backdrop bg_skills={41,40};
#define bg_bag_palette (reinterpret_cast<const uint16_t*>(assetBytes(42)))
#define bg_bag_pixels (reinterpret_cast<const uint8_t*>(assetBytes(43)))
const Backdrop bg_bag={43,42};
#define bg_townbag_palette (reinterpret_cast<const uint16_t*>(assetBytes(44)))
#define bg_townbag_pixels (reinterpret_cast<const uint8_t*>(assetBytes(45)))
const Backdrop bg_townbag={45,44};
#define bg_saveerror_palette (reinterpret_cast<const uint16_t*>(assetBytes(46)))
#define bg_saveerror_pixels (reinterpret_cast<const uint8_t*>(assetBytes(47)))
const Backdrop bg_saveerror={47,46};
#define bg_blocked_palette (reinterpret_cast<const uint16_t*>(assetBytes(48)))
#define bg_blocked_pixels (reinterpret_cast<const uint8_t*>(assetBytes(49)))
const Backdrop bg_blocked={49,48};
#define bg_won_palette (reinterpret_cast<const uint16_t*>(assetBytes(50)))
#define bg_won_pixels (reinterpret_cast<const uint8_t*>(assetBytes(51)))
const Backdrop bg_won={51,50};
#define bg_lost_palette (reinterpret_cast<const uint16_t*>(assetBytes(52)))
#define bg_lost_pixels (reinterpret_cast<const uint8_t*>(assetBytes(53)))
const Backdrop bg_lost={53,52};
#define bg_fled_palette (reinterpret_cast<const uint16_t*>(assetBytes(54)))
#define bg_fled_pixels (reinterpret_cast<const uint8_t*>(assetBytes(55)))
const Backdrop bg_fled={55,54};
#define bg_battle0_palette (reinterpret_cast<const uint16_t*>(assetBytes(56)))
#define bg_battle0_pixels (reinterpret_cast<const uint8_t*>(assetBytes(57)))
const Backdrop bg_battle0={57,56};
#define bg_battle1_palette (reinterpret_cast<const uint16_t*>(assetBytes(58)))
#define bg_battle1_pixels (reinterpret_cast<const uint8_t*>(assetBytes(59)))
const Backdrop bg_battle1={59,58};
#define bg_battle2_palette (reinterpret_cast<const uint16_t*>(assetBytes(60)))
#define bg_battle2_pixels (reinterpret_cast<const uint8_t*>(assetBytes(61)))
const Backdrop bg_battle2={61,60};
#define bg_battle3_palette (reinterpret_cast<const uint16_t*>(assetBytes(62)))
#define bg_battle3_pixels (reinterpret_cast<const uint8_t*>(assetBytes(63)))
const Backdrop bg_battle3={63,62};
template<class Canvas> void drawBackdrop(Canvas& c,const Backdrop& bg){uint16_t stripe[480];for(int y=0;y<160;++y){for(int x=0;x<120;++x){uint16_t color=bg.palette()[bg.pixels()[y*120+x]];stripe[x*2]=stripe[x*2+1]=stripe[240+x*2]=stripe[241+x*2]=color;}c.draw16bitRGBBitmap(0,y*2,stripe,240,2);}}

const Backdrop bg_tests={154,153};
const Backdrop bg_world={156,155};
const Backdrop bg_menu={158,157};
const Backdrop bg_slots={160,159};
const Backdrop bg_slotconfirm={162,161};
const Backdrop bg_delete={164,163};
const Backdrop bg_settings={166,165};
const Backdrop bg_wifi={168,167};
const Backdrop bg_keyboard={170,169};
const Backdrop bg_port={172,171};
const Backdrop bg_castle={174,173};
const Backdrop bg_guild={176,175};
const Backdrop bg_guildjoin={178,177};
const Backdrop bg_missions={180,179};
const Backdrop bg_race={182,181};
const Backdrop bg_clothes={184,183};
const Backdrop bg_club={186,185};
const Backdrop bg_clubbattle={188,187};
const Backdrop bg_clubresult={190,189};
const Backdrop bg_updates={192,191};
