#pragma once
#include "Narrative.h"
namespace story {
// Continuous speech, selected from facts already recorded for this hero.
inline const char* conversation(const rpg::Game& g,unsigned person){
 person%=3;
 if(g.campaignEnding==2)return g.city==0?"O sino tocou porque Nara estava la. As raizes voltaram a crescer, e agora podemos lembrar quem nos ensinou a cuidar delas. Voce ajudou a devolver o amanha a Carvalho. Descanse quando precisar; esta cidade continua sendo sua casa.":g.city==1?"Os nomes recuperados chegaram as familias. Vespera ainda tem perigos, mas ja nao guarda a mesma mentira. Uma nova expedicao pode recuperar o que ficou para tras sem aprisionar outras memorias.":g.city==2?"As rotas dos farois continuam abertas. Os voluntarios voltaram com historias para contar, e o porto recebeu suas familias. Ha trabalho para a Guilda e noticias das ilhas; nada disso apaga o que voce fez por Aeldra.":"Odran responde por suas ordens. A nova estrutura sustenta os farois sem celas nem prisioneiros. Nosso trabalho agora e cuidar do que reconstruimos. Aeldra nao ficou sem perigos; ficou livre para escolher como enfrenta-los.";

 if(g.city==3&&person==0&&(g.campaignFlags&128))return g.campaignEnding==1?"O selo nos deu tempo, mas ainda depende do velho Pacto. Odran permanece sob custodia. Nao vamos retirar mais lembrancas das familias. Reuna as ajudas que faltam no diario; quando estiverem prontas, volte a mim. Enfrentaremos o Coracao do Veu outra vez e sustentaremos os farois com o trabalho dos aliados. Sua primeira vitoria nao foi perdida.":"Odran perdeu o poder. No salao, o Coracao do Veu ainda mantem a fenda aberta. Nao e o proprio Veu: e sua manifestacao aqui. Derrota-lo permitira fechar o mecanismo, mas so os quatro farois reconstruidos podem sustentar o selo sem roubar memorias. Recupere suas forcas e confira a bolsa antes de entrar. Com todas as ajudas, podemos restaurar; sem elas, ganharemos tempo para voltar e completa-las.";
 if((g.campaignFlags&7)==7&&person==rpg::campaignPerson(4+g.city)){
  if(rpg::contribution(g,g.city))return contributionSpeech(4+g.city);
  if(g.city==0)return "Borin mostrou o desenho de Anwen. Ainda ha raizes vivas sob a cinza, mas precisamos cuidar delas ate a restauracao. Traga tres racoes para alimentar os voluntarios; eu preparo as mudas. Nara ofereceu o abrigo, e Borin vai levar as ferramentas. Esta sera a ajuda de Carvalho. Nao precisa tirar comida da propria boca: compre as provisoes e volte quando estiver pronto.";
  if(g.city==1)return "O Livro explicou o pacto, mas os nomes das vitimas ainda estao presos aos registros. Preciso abrir uma sala antiga; um espectro continua guardando a porta. Venha comigo e mantenha-o longe enquanto liberto as memorias. Nao vamos consumir esses ecos para acender outro farol. Vamos devolver a cada lembranca o direito de partir ou de voltar para casa.";
  if(g.city==2)return "Tenho uma equipe pronta para trabalhar nos farois. Sao voluntarios, inclusive algumas pessoas que voce resgatou. A Mao de Cinza bloqueou o cais para impedir nossa partida. Preciso que nos escolte ate a rota segura; Sabela cuidara do porto enquanto estivermos fora. Depois de tanto transportar caixas fechadas, Mares vai levar gente que sabe por que esta viajando.";
  return "O projeto de Anwen precisa de uma estrutura nova, sem as celas do mecanismo antigo. Seraphine reunira os juramentos voluntarios; eu construo a parte que deve sustenta-los. Os componentes custam cento e cinquenta moedas. Minha equipe oferece o trabalho. Confira sua bolsa e decida quando puder ajudar; nao vou tomar sua arma nem sua armadura para montar o farol.";
 }
 if(rpg::anwenReady(g)&&g.city==3&&person==0)return "As quatro ajudas estao prontas. O Veu Oco apaga nomes e vinculos; um golpe nao pode destruir essa forca. Os farois sustentam o selo da fenda. Anwen descobriu como alimenta-los com terra viva e juramentos livres, em vez de memorias roubadas. Voce reuniu quem pode reconstruir esse mecanismo. Primeiro impediremos Odran de iniciar a Vigilia. Depois enfrentaremos o Coracao do Veu, e os aliados manterao o selo enquanto voce luta.";

 if(g.city==0){
  if(person==0){if(g.campaignFlags&4)return "Sente um pouco. Voce trouxe a verdade de Aurora, mas ainda precisa comer. Nao vou deixar que enfrente um rei de barriga vazia. Quando tudo acabar, quero ouvir sua historia aqui, ao lado do fogo, com todos os nomes que o Pacto tentou apagar.";
   if(arconteKnown(g))return "Eu achava que estava ficando velha quando esqueci quem me ensinou esta receita. Agora voce diz que os cristais levavam nossas lembrancas... Entendo por que Iria mandou voce a Mares. Procure Sabela no porto. E volte para me contar o que descobrir; sua cama continua aqui.";
   return "Entre, a sopa ainda esta quente. Voce empurrou aquela carroca ate o portao quando podia ter seguido seu caminho. Carvalho precisa de gente assim. Elarin viu cinza nas raizes, e Borin encontrou o mesmo material numa peca antiga. Fale com os dois. Antes de partir para as Ruinas, prepare sua bolsa. Quero ver voce voltar inteiro.";}
  if(person==1)return arconteKnown(g)?"Voce encontrou a causa da cinza. Isso nao devolve a primavera de uma vez, mas agora temos por onde comecar. Vou cuidar das mudas enquanto voce segue a pista dos cristais em Mares. Leve racoes; ate quem sabe lutar precisa comer. Se o Pacto nasceu da terra, a terra tambem pode nos ajudar a fazer algo melhor.":"Veja esta raiz. Por fora parece saudavel; por dentro esta fria e coberta de cinza. Os lobos nao vieram nos atacar por maldade. Estao fugindo do bosque e procurando comida. Borin reconheceu este material. Fale com ele antes de investigar Vespera. Eu fico cuidando das plantas e das familias que dependem delas.";
  return arconteKnown(g)?"Passei a vida me orgulhando dos farois que meus antepassados construiram. O Livro que voce encontrou me obriga a olhar para essa obra de outro jeito. Uma maquina que rouba a vida das pessoas precisa ser corrigida, nao celebrada. Leve suas provas a Sabela. Eu mantenho minha forja acesa para quem vai enfrentar esse problema.":"Deixe eu ver essa cinza... Encontrei algo parecido preso numa peca de farol. Meus antepassados fizeram esse mecanismo, mas os desenhos chegaram incompletos ate mim. Iria pesquisa as Ruinas de Vespera. Ela pode reconhecer a peca. Prepare sua arma antes de partir; os mortos de la ainda obedecem a ordens antigas.";
 }
 if(g.city==1){
  if(person==0){if(arconteKnown(g))return "O Livro conta que uma fenda se abriu sob Vespera ha cento e vinte anos. Dela veio o Veu Oco: os mortos retornam incompletos, e os vivos perdem nomes e vinculos. Os quatro farois fecharam a fenda, mas seus cristais consomem memorias para manter o selo. Quando se apagam, a fenda volta a ceder. Sabela investiga cargas desses cristais em Mares. Leve a verdade a ela; nao podemos esconder esse preco outra vez.";
   if(g.guardianDefeated)return "Voce venceu o Guardiao, mas ele nao era o Arconte. Era a defesa externa do Farol da Memoria. O cristal que conseguiu abre a Cripta de Vaelor. La dentro, procure os selos para avancar pelos dois andares. Nao confunda o ouro do bau com a resposta que buscamos: precisamos saber por que essas defesas continuam lutando.";
   return "Bem-vindo a Vespera. As pessoas a chamam de Ruinas, mas cada pedra aqui pertenceu a uma casa. Os mortos repetem ordens que receberam ha muito tempo. Investigue os encontros deste lugar; depois de tres vitorias, podera enfrentar o Guardiao do Limiar. Eu vou ajudar a entender o que ele protege. Nao entre sem provisoes.";}
  if(person==1)return "Esta racao veio numa caravana que precisou de escolta ate o ultimo trecho. Por isso custa mais que em Carvalho. Eu avalio armas recuperadas e preparo cargas para as expedicoes de Iria. Se achar uma reliquia, olhe bem antes de vende-la. Algumas sao so equipamento; outras carregam a historia de quem nao conseguiu voltar.";
  return arconteKnown(g)?"Eu ajudei a fechar a fenda. A Raiz ligava a terra; a Memoria guardava os nomes; o Caminho unia as rotas; o Juramento sustentava o conjunto. Chamamos isso de Pacto da Primeira Aurora. Escondemos seu preco: a cada noite os cristais consumiam lembrancas de pessoas vivas. Quebrar todos os farois libertaria o Veu Oco. Precisamos reconstruir o que os alimenta, nao abandonar o selo. Leve o Livro e encontre outro caminho.":"Ha uma voz alem dos selos da Cripta, mas voce ainda nao encontrou quem fala. Iria pode explicar como entrar. Primeiro sera preciso atravessar a defesa do Guardiao e conseguir um cristal.";
 }
 if(g.city==2){
  if(person==0){if(g.campaignFlags&4)return "Liora encontrou as ordens? Entao chegamos a quem mandava essas cargas. O porto continua aberto aos refugiados. Voce nao lutou por caixas de cristal: lutou para que aquelas pessoas pudessem chegar vivas. Leve essa lembranca com voce quando voltar a Aurora. A Coroa precisa responder pelo que fez.";
   if((g.campaignFlags&3)==3)return "Olhe as oficinas: os refugiados ja estao la, aquecidos e alimentados. Nilsa religou o Farol do Caminho. Voce nos deu tempo para salvar gente. Maelis enviou os registros da Guilda; leve-os, junto com o Livro, a Liora em Aurora. O selo das cargas era da Coroa. Ela precisa saber o que o pai autorizou.";
   if(g.campaignFlags&1)return "As caixas que recuperamos traziam nomes riscados, e os registros ligam a carga a Coroa. Maelis admitiu que financiou aquelas rotas sem perguntar o que transportavam. Agora o farol apagou. Um barco de refugiados bateu no cais, e a Mao de Cinza bloqueia a passagem. Preciso que abra caminho; minha guarda fara o resgate.";
   return arconteKnown(g)?"Iria avisou que voce traria o Livro. Aqui os navios voltam sem tripulacao, e a Mao de Cinza leva cristais pelas cisternas. Preciso de provas para agir contra quem paga por isso. Ajude-nos a atravessar a escolta da carga. Minha guarda recolhera as caixas; voce nao precisa achar a pista por sorte num saque.":"Voce chegou num dia dificil. Ha navios voltando sem tripulacao e familias esperando no cais. A Mao de Cinza negocia cristais, mas ainda nao tenho provas do que fazem. Iria procura respostas nas Ruinas. Se descobrir o que esses cristais guardam, traga a verdade ao porto. Eu nao vou abandonar quem ficou esperando.";}
  if(person==1)return g.campaignFlags&1?"Reconheci a marca da Coroa nas cargas. Eu mesmo levei algumas e aceitei dinheiro sem perguntar o que havia dentro. Nao tenho orgulho disso. Entreguei minhas rotas a Sabela; agora ela pode chegar as cisternas. Se precisar viajar, ainda vendo mapas e provisoes. Desta vez, quero saber quem chega ao outro lado.":"Um mapa nao vale muito quando a estrada deixa de levar ao lugar desenhado. As mares mudaram, e ha mercadores que preferem arriscar cargas suspeitas a voltar sem dinheiro. Vendo provisoes e equipamento trazido de outros portos. Sabela investiga os desaparecimentos. Se puder ajuda-la, talvez eu volte a confiar nas rotas que desenho.";
  return (g.campaignFlags&2)?"As pecas que encontramos dentro dos cascos pertenciam ao farol. Alguem as retirou de proposito. Enquanto voce abria a passagem, consegui reconectar a rota segura. O Caminho voltou a responder. Os refugiados estao nas minhas oficinas. Nao sei como enfrentaremos a Coroa ainda, mas estas pessoas vao dormir abrigadas hoje.":"Trabalho com cascos de navio, e sei quando uma peca nao pertence a eles. Achei componentes de farol escondidos em madeira nova. Alguem quer tirar essas pecas de Mares sem ser visto. Sabela esta seguindo a carga. Traga suas armas se precisar de reparo; eu nao vou deixar que enfrente essa gente com equipamento quebrado.";
 }
 if(person==0){if(g.campaignFlags&4)return "Meu pai escreveu uma ordem para me proteger, porque ja nao lembrava meu rosto. Eu queria acreditar que isso explicava tudo. Mas foi ele quem decidiu cobrar as lembrancas de outras familias. Voce abriu os arquivos e me deu a verdade. Vou ficar ao seu lado para impedir a Vigilia. Seraphine e Dargan conhecem o projeto de Anwen; precisamos ouvir os dois.";
  return (g.campaignFlags&3)==3?"Sabela enviou noticias do resgate, e recebi os registros de Maelis. Obrigada por trazer o Livro ate aqui. Meu pai sabia o preco do Pacto. Os arquivos guardam as ordens que ele assinou, mas uma sentinela impede nossa entrada. Preciso que abra caminho. Seraphine, Dargan e eu recolheremos os documentos. Prepare-se bem; a sentinela nao conhece misericordia.":"As ruas parecem tranquilas, mas a guarda repete ordens que ninguem consegue explicar. Meu pai perdeu muitas lembrancas. Eu preciso saber quais decisoes ainda toma por vontade propria. Sabela investiga cargas da Coroa em Mares. Ajude-a primeiro e traga os registros. Sem provas, eu so teria suspeitas contra o homem que me criou.";}
 if(person==1)return g.campaignFlags&4?"Li a ordem da Vigilia. Odran quer prender o reino num amanhecer que consumira as lembrancas de todos. Anwen tentou outro caminho: terra viva, vinculos voluntarios e juramentos renovados. Dargan protege seu desenho. Vamos precisar dos quatro farois para completa-lo. Voce reuniu pessoas que antes nem sabiam por que sofriam. Isso importa tanto quanto sua arma.":"Quando alguem faz um juramento, promete proteger algo que importa. Obedecer a uma ordem cruel nao torna essa promessa mais sagrada. Liora quer descobrir o que aconteceu com o pai e com nossos farois. Traga a ela as provas de Mares. Eu ajudarei a ler os registros; nao vou usar o templo para justificar mais sacrificios.";
 return g.campaignFlags&4?"Guardei o desenho de Anwen entre minhas ferramentas porque a Coroa procurava planos de armas, nao de reparo. Ele mostra como sustentar o selo sem aprisionar pessoas. Ainda precisamos do trabalho das quatro cidades. Voce protegeu o arquivo; agora eu protejo esse desenho. Minha lealdade e com o povo que usa esta forja, nao com quem paga minha oficina.":"Aurora tem boas oficinas, mas a Coroa compra cristais a qualquer custo. Eu nao gosto de perguntas que precisam ser feitas em voz baixa. Liora esta tentando entrar nos arquivos. Ajude-a depois de conseguir as provas de Mares. Enquanto isso, posso preparar seu equipamento. Sentinelas nao perguntam por que voce esta diante delas.";
}
inline unsigned conversationPages(const char* text){return std::max(1u,(wrapStory(text,18,[](unsigned,const char*){})+6)/7);}
}
