// Generated by tools/prepare_gear.py from supplied item sheets.
#pragma once
#include <stdint.h>
#include "AssetCatalog.h"
#define gear_icon_cajado (reinterpret_cast<const uint16_t*>(assetBytes(147)))
#define gear_icon_espada (reinterpret_cast<const uint16_t*>(assetBytes(148)))
#define gear_icon_lanca (reinterpret_cast<const uint16_t*>(assetBytes(149)))
#define gear_icon_machado (reinterpret_cast<const uint16_t*>(assetBytes(150)))
#define gear_icon_armadura (reinterpret_cast<const uint16_t*>(assetBytes(151)))
#define gear_icon_amuleto (reinterpret_cast<const uint16_t*>(assetBytes(152)))
inline const uint16_t* const* gear_icons_get(){static const uint16_t* const a[]={gear_icon_cajado,gear_icon_espada,gear_icon_lanca,gear_icon_machado,gear_icon_armadura,gear_icon_amuleto};return a;}
#define gear_icons (gear_icons_get())
