#pragma once
#include <HTTPClient.h>
#include <NetworkClientSecure.h>
#include <esp_ota_ops.h>
#include <mbedtls/sha256.h>
#include <cJSON.h>
#include <time.h>
#include "UpdateModel.h"
// Network runs in a worker; only SD/LCD SPI operations share this mutex.
inline SemaphoreHandle_t updateSpi=nullptr,updateGuard=nullptr;
inline updater::Info updateWorker;inline updater::Plan updatePlan;
struct UpdateSpiLock {UpdateSpiLock(){if(updateSpi)xSemaphoreTake(updateSpi,portMAX_DELAY);}~UpdateSpiLock(){if(updateSpi)xSemaphoreGive(updateSpi);}};
inline void initUpdater(){updateSpi=xSemaphoreCreateMutex();updateGuard=xSemaphoreCreateMutex();}
inline void updateReport(updater::State state,const char* msg,unsigned percent=0,bool busy=true){xSemaphoreTake(updateGuard,portMAX_DELAY);updateWorker.state=state;updateWorker.progress=percent;updateWorker.busy=busy;snprintf(updateWorker.message,sizeof(updateWorker.message),"%s",msg);xSemaphoreGive(updateGuard);}
inline bool tickUpdater(){if(!updateGuard)return false;xSemaphoreTake(updateGuard,portMAX_DELAY);bool changed=memcmp(&updateInfo,&updateWorker,sizeof(updateInfo))!=0;updateInfo=updateWorker;xSemaphoreGive(updateGuard);return changed;}
inline bool updateFail(const char* s){updateReport(updater::State::Error,s,0,false);return false;}
inline bool jsonString(cJSON* o,const char* key,char* out,size_t n){auto v=cJSON_GetObjectItemCaseSensitive(o,key);if(!cJSON_IsString(v)||!v->valuestring||strlen(v->valuestring)>=n)return false;strcpy(out,v->valuestring);return true;}
inline bool jsonNumber(cJSON* o,const char* key,uint32_t& out){auto v=cJSON_GetObjectItemCaseSensitive(o,key);if(!cJSON_IsNumber(v)||v->valuedouble<0||v->valuedouble>UINT32_MAX||double(uint32_t(v->valuedouble))!=v->valuedouble)return false;out=uint32_t(v->valuedouble);return true;}
inline bool jsonPackage(cJSON* o,const char* key,updater::Package& p){auto v=cJSON_GetObjectItemCaseSensitive(o,key);return cJSON_IsObject(v)&&jsonString(v,"url",p.url,sizeof(p.url))&&jsonString(v,"sha256",p.sha,sizeof(p.sha))&&jsonNumber(v,"bytes",p.bytes);}
inline bool parseUpdate(const char* body,updater::Plan& p){cJSON* j=cJSON_Parse(body);if(!j)return false;char board[40],partition[40],crc[9];uint32_t schema=0;bool ok=jsonNumber(j,"schema",schema)&&schema==2&&jsonString(j,"board",board,sizeof(board))&&!strcmp(board,"Waveshare-29667")&&jsonString(j,"partition",partition,sizeof(partition))&&!strcmp(partition,"app3M_fat9M_16MB")&&jsonString(j,"version",p.version,sizeof(p.version))&&jsonNumber(j,"build",p.build)&&jsonNumber(j,"save_format",p.saveFormat)&&jsonPackage(j,"firmware",p.firmware)&&jsonPackage(j,"art",p.art)&&jsonNumber(cJSON_GetObjectItemCaseSensitive(j,"art"),"assets",p.assets)&&jsonString(cJSON_GetObjectItemCaseSensitive(j,"art"),"payload_crc32",crc,sizeof(crc));
  if(ok){if(strlen(crc)!=8)ok=false;else for(unsigned i=0;i<8;++i)if(!((crc[i]>='0'&&crc[i]<='9')||(crc[i]>='a'&&crc[i]<='f')))ok=false;p.artCrc=strtoul(crc,nullptr,16);}cJSON_Delete(j);return ok;}
inline bool tlsUrl(const String& s){return s.startsWith("https://github.com/")||s.startsWith("https://release-assets.githubusercontent.com/")||s.startsWith("https://objects.githubusercontent.com/");}
inline int openUpdateHttp(HTTPClient& h,NetworkClientSecure& tls,const char* url){tls.useBuiltinCACertBundle();tls.setHandshakeTimeout(20);String next(url);for(unsigned redirects=0;redirects<6;++redirects){if(!tlsUrl(next))return -1;if(!h.begin(tls,next))return -1;h.setConnectTimeout(15000);h.setTimeout(15000);h.setFollowRedirects(HTTPC_DISABLE_FOLLOW_REDIRECTS);const char* keys[]={"Location"};h.collectHeaders(keys,1);int rc=h.GET();if(rc==301||rc==302||rc==303||rc==307||rc==308){next=h.header("Location");h.end();continue;}return rc;}return -1;}
inline bool updateTime(){configTime(0,0,"pool.ntp.org","time.google.com");uint32_t start=millis();while(time(nullptr)<1767225600){if(WiFi.status()!=WL_CONNECTED||millis()-start>20000)return false;vTaskDelay(pdMS_TO_TICKS(100));}return true;}
inline bool readNetwork(HTTPClient& http,uint8_t* buffer,size_t n){auto stream=http.getStreamPtr();size_t off=0;uint32_t last=millis();while(off<n){int available=stream->available();if(available>0){int got=stream->read(buffer+off,std::min(n-off,size_t(available)));if(got<=0)return false;off+=got;last=millis();}else{if(!http.connected()||WiFi.status()!=WL_CONNECTED||millis()-last>15000)return false;vTaskDelay(pdMS_TO_TICKS(2));}}return true;}
inline bool fileHash(const char* path,const char* expected,uint32_t bytes,bool art=false){File f;{UpdateSpiLock lock;f=SD.open(path,FILE_READ);if(!f||f.size()!=bytes){if(f)f.close();return false;}}uint8_t buffer[4096],header[16];mbedtls_sha256_context ctx;mbedtls_sha256_init(&ctx);mbedtls_sha256_starts(&ctx,0);uint32_t remain=bytes,crc=~0u,offset=0;bool good=true;
  while(remain){size_t n=std::min(remain,uint32_t(sizeof(buffer)));{UpdateSpiLock lock;if(f.read(buffer,n)!=int(n)){good=false;break;}}mbedtls_sha256_update(&ctx,buffer,n);if(art){if(offset==0)memcpy(header,buffer,16);for(size_t i=offset==0?16:0;i<n;++i){crc^=buffer[i];for(unsigned bit=0;bit<8;++bit)crc=(crc>>1)^(0xedb88320u&uint32_t(-int(crc&1)));}}offset+=n;remain-=n;vTaskDelay(1);}
  uint8_t digest[32];mbedtls_sha256_finish(&ctx,digest);mbedtls_sha256_free(&ctx);{UpdateSpiLock lock;f.close();}char hash[65];for(unsigned i=0;i<32;++i)snprintf(hash+2*i,3,"%02x",digest[i]);
  if(art)good=good&&!memcmp(header,"PKA1",4)&&rpg::get32(header,4)==bytes-16&&rpg::get32(header,8)==updatePlan.artCrc&&rpg::get32(header,12)==updatePlan.assets&&~crc==updatePlan.artCrc;return good&&!strcmp(hash,expected);
}
inline bool downloadUpdate(const updater::Package& p,const char* path,unsigned base,unsigned span){NetworkClientSecure tls;HTTPClient http;int rc=openUpdateHttp(http,tls,p.url);if(rc!=200||http.getSize()!=int(p.bytes)){http.end();return false;}File out;{UpdateSpiLock lock;if(SD.exists(path)&&!SD.remove(path)){http.end();return false;}out=SD.open(path,FILE_WRITE);}if(!out){http.end();return false;}
  uint8_t buffer[4096];uint32_t downloaded=0;bool ok=true;while(downloaded<p.bytes){size_t n=std::min(uint32_t(sizeof(buffer)),p.bytes-downloaded);if(!readNetwork(http,buffer,n)){ok=false;break;}{UpdateSpiLock lock;if(out.write(buffer,n)!=n){ok=false;break;}}downloaded+=n;updateReport(updater::State::Downloading,"Mantenha a alimentacao",base+uint64_t(downloaded)*span/p.bytes);vTaskDelay(1);} {UpdateSpiLock lock;out.flush();out.close();}http.end();return ok;
}
inline void checkUpdate(){using namespace updater;if(!updateTime()){updateFail("Sem horario seguro / confira Wi-Fi");return;}NetworkClientSecure tls;HTTPClient http;int rc=openUpdateHttp(http,tls,"https://github.com/Oflodorporto/RPG-POKET-2/releases/latest/download/manifest.json");if(rc==404){http.end();updateFail("Ainda nao ha versao publicada");return;}int length=http.getSize();if(rc!=200||length<=0||length>4096){http.end();updateFail("Nao foi possivel verificar");return;}char body[4097];bool got=readNetwork(http,reinterpret_cast<uint8_t*>(body),length);http.end();body[length]=0;Plan p;const esp_partition_t* target=esp_ota_get_next_update_partition(nullptr);
  if(!got||!parseUpdate(body,p)||!target||!valid(p,target->size,ESP.getPsramSize())||(p.build==FW_BUILD&&(strcmp(p.version,FW_VERSION)||p.artCrc!=ART_CRC||p.assets!=ART_COUNT||p.art.bytes!=ART_BYTES+16))){updateFail("Manifesto incompativel / invalido");return;}
  updatePlan=p;xSemaphoreTake(updateGuard,portMAX_DELAY);snprintf(updateWorker.version,sizeof(updateWorker.version),"%s",p.version);updateWorker.artOnly=p.build==FW_BUILD;bool needed=p.build>FW_BUILD||menu.art!=ArtStatus::Ready||p.artCrc!=ART_CRC;updateWorker.state=needed?State::Available:State::Current;updateWorker.busy=false;snprintf(updateWorker.message,sizeof(updateWorker.message),"%s",needed?"Confirmar para baixar e instalar":"Voce ja tem a versao atual");xSemaphoreGive(updateGuard);
}
// Return from the C++ scope first so HTTP/TLS destructors free their heap.
inline void updateCheckTask(void*){checkUpdate();vTaskDelete(nullptr);}
inline bool installUpdate(bool artOnly){using namespace updater;const char* firmwarePart="/RPGPOKET/firmware.part";const char* artPart="/RPGPOKET/artes.part";char finalArt[48];artPath(finalArt,sizeof(finalArt),updatePlan.artCrc);
  {UpdateSpiLock lock;digitalWrite(45,HIGH);digitalWrite(41,HIGH);if(!SD.begin(41,SPI,4000000,"/sd",1,false)){SD.end();return updateFail("Cartao indisponivel");}if(!SD.exists("/RPGPOKET")&&!SD.mkdir("/RPGPOKET")){SD.end();return updateFail("Nao foi possivel preparar cartao");}SD.remove(firmwarePart);SD.remove(artPart);uint64_t needed=uint64_t(updatePlan.art.bytes)+(artOnly?0:updatePlan.firmware.bytes)+1048576;uint64_t total=SD.totalBytes(),used=SD.usedBytes();if(total<used||total-used<needed){SD.end();return updateFail("Sem espaco livre no cartao");}}
  bool ok=true;if(!artOnly)ok=downloadUpdate(updatePlan.firmware,firmwarePart,0,25);if(ok)ok=downloadUpdate(updatePlan.art,artPart,artOnly?0:25,artOnly?80:55);
  updateReport(State::Verifying,"Conferindo SHA-256 e artes",80);if(ok&&!artOnly)ok=fileHash(firmwarePart,updatePlan.firmware.sha,updatePlan.firmware.bytes);if(ok)ok=fileHash(artPart,updatePlan.art.sha,updatePlan.art.bytes,true);
  if(!ok){UpdateSpiLock lock;SD.remove(firmwarePart);SD.remove(artPart);SD.end();return updateFail("Download incompleto / tente de novo");}
  // Publish a verified versioned art file; the current file is never overwritten.
  bool existing=false;{UpdateSpiLock lock;existing=SD.exists(finalArt);}bool reuse=existing&&fileHash(finalArt,updatePlan.art.sha,updatePlan.art.bytes,true);
  {UpdateSpiLock lock;if(reuse)ok=SD.remove(artPart);else{if(existing)ok=SD.remove(finalArt);if(ok)ok=SD.rename(artPart,finalArt);}}if(ok)ok=fileHash(finalArt,updatePlan.art.sha,updatePlan.art.bytes,true);
  const esp_partition_t* target=esp_ota_get_next_update_partition(nullptr);esp_ota_handle_t handle=0;bool opened=false;
  if(ok&&!artOnly){updateReport(State::Installing,"Instalando na particao livre",85);ok=target&&esp_ota_begin(target,updatePlan.firmware.bytes,&handle)==ESP_OK;opened=ok;File f;if(ok){UpdateSpiLock lock;f=SD.open(firmwarePart,FILE_READ);ok=bool(f);}uint8_t buffer[4096];uint32_t copied=0;while(ok&&copied<updatePlan.firmware.bytes){size_t n=std::min(uint32_t(sizeof(buffer)),updatePlan.firmware.bytes-copied);{UpdateSpiLock lock;ok=f.read(buffer,n)==int(n);}if(ok)ok=esp_ota_write(handle,buffer,n)==ESP_OK;copied+=n;updateReport(State::Installing,"Instalando na particao livre",85+uint64_t(copied)*10/updatePlan.firmware.bytes);vTaskDelay(1);}if(f){UpdateSpiLock lock;f.close();}if(ok){ok=esp_ota_end(handle)==ESP_OK;opened=false;}if(opened)esp_ota_abort(handle);}
  updateReport(State::Cleaning,"Removendo arquivos temporarios",96);{UpdateSpiLock lock;SD.remove(firmwarePart);SD.remove(artPart);SD.end();digitalWrite(41,HIGH);digitalWrite(45,HIGH);}
  if(!ok)return updateFail("Instalacao falhou / jogo preservado");
  // Select the new boot slot only after both artifacts passed verification.
  if(!artOnly&&esp_ota_set_boot_partition(target)!=ESP_OK)return updateFail("Nao foi possivel ativar a versao");updateReport(State::Restarting,"Atualizado / reiniciando",100);vTaskDelay(pdMS_TO_TICKS(1800));ESP.restart();return true;
}
inline void updateInstallTask(void*){installUpdate(updatePlan.build==FW_BUILD);vTaskDelete(nullptr);}
inline bool startUpdate(bool install){if(!updateGuard||!updateSpi||updateInfo.busy)return false;if(WiFi.status()!=WL_CONNECTED){updateFail("Conecte o Wi-Fi primeiro");tickUpdater();return false;}if(install&&updateInfo.state!=updater::State::Available)return false;updateReport(install?updater::State::Downloading:updater::State::Checking,install?"Preparando arquivos...":"Consultando GitHub...",0,true);tickUpdater();if(xTaskCreate(install?updateInstallTask:updateCheckTask,"rpg-update",24576,nullptr,1,nullptr)!=pdPASS){updateFail("Memoria insuficiente para atualizar");tickUpdater();return false;}return true;}

inline void resetUpdateScreen(){if(!updateGuard||updateInfo.busy)return;xSemaphoreTake(updateGuard,portMAX_DELAY);updateWorker=updater::Info{};updateInfo=updateWorker;xSemaphoreGive(updateGuard);}
